/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eventos_grupo3;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.MenuDragMouseEvent;
import javax.swing.event.MenuDragMouseListener;
import javax.swing.event.MenuEvent;
import javax.swing.event.MenuListener;

/**
 *
 * @author kriz_
 */
public class JFrmEventos extends javax.swing.JFrame implements WindowListener, ComponentListener, ActionListener, MenuListener, KeyListener, FocusListener, ChangeListener, MenuDragMouseListener {

    /**
     * Creates new form JFrmEventos
     */
    public JFrmEventos() {
        initComponents();
        setLocationRelativeTo(null);
        jRdBtnSpanish.setSelected(true);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(this);
        setBackground(Color.GREEN);
        jBtnAceptar.addActionListener(this);
        jBtnCancelar.addActionListener(this);
        jBtnMetPago.addActionListener(this);
        jBtnMenu.addActionListener(this);
        jBtnBorrar.addActionListener(this);
        jMhelp.addMenuListener(this);
        jTxfCedula.addKeyListener(this);
        jTxfNombre.addKeyListener(this);
        jTxfApellido.addKeyListener(this);
        jTxfMtdoPago.addKeyListener(this);
        jTxfOrden.addKeyListener(this);
        jBtnAceptar.addKeyListener(this);
        jBtnCancelar.addKeyListener(this);
        jBtnMetPago.addKeyListener(this);
        jBtnMenu.addKeyListener(this);
        jBtnBorrar.addKeyListener(this);
        jBtnAceptar.addFocusListener(this);
        jRdBtnSpanish.addChangeListener(this);
        jRdBtnEnglish.addChangeListener(this);
        jRdBtnFrancais.addChangeListener(this);
        addComponentListener(this);

    }

    private int x;
    private int y;
    
    public void setFont() {
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, x / 20));
        jLblNombre.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jLblApellido.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jLblOrden.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jLblMtdoPago.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jLblNOrden1.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jLblCedula.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jLblNOrden.setFont(new java.awt.Font("Times New Roman", 2, (x / 13) - jLabel1.getFont().getSize()));
        jTxfNombre.setFont(new java.awt.Font("Times New Roman", 0, (x / 13) - jLabel1.getFont().getSize()));
        jTxfApellido.setFont(new java.awt.Font("Times New Roman", 0, (x / 13) - jLabel1.getFont().getSize()));
        jTxfCedula.setFont(new java.awt.Font("Times New Roman", 0, (x / 13) - jLabel1.getFont().getSize()));
        jTxfMtdoPago.setFont(new java.awt.Font("Times New Roman", 0, (x / 13) - jLabel1.getFont().getSize()));
        jTxfOrden.setFont(new java.awt.Font("Times New Roman", 0, (x / 13) - jLabel1.getFont().getSize()));
        jBtnAceptar.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jBtnCancelar.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jBtnBorrar.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jBtnMenu.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jBtnMetPago.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jRdBtnSpanish.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jRdBtnEnglish.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
        jRdBtnFrancais.setFont(new java.awt.Font("Times New Roman", 3, (x / 13) - jLabel1.getFont().getSize()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblApellido = new javax.swing.JLabel();
        jLblOrden = new javax.swing.JLabel();
        jTxfNombre = new javax.swing.JTextField();
        jTxfApellido = new javax.swing.JTextField();
        jTxfCedula = new javax.swing.JTextField();
        jBtnAceptar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jBtnMetPago = new javax.swing.JButton();
        jBtnBorrar = new javax.swing.JButton();
        jBtnMenu = new javax.swing.JButton();
        jLblCedula = new javax.swing.JLabel();
        jTxfOrden = new javax.swing.JTextField();
        jLblMtdoPago = new javax.swing.JLabel();
        jTxfMtdoPago = new javax.swing.JTextField();
        jLblNOrden = new javax.swing.JLabel();
        jLblNOrden1 = new javax.swing.JLabel();
        jRdBtnFrancais = new javax.swing.JRadioButton();
        jRdBtnSpanish = new javax.swing.JRadioButton();
        jRdBtnEnglish = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMnImPagWb = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnImSalir = new javax.swing.JMenuItem();
        jMhelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 0, 51));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel1.setText("KrustyBurguer");

        jLblNombre.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLblNombre.setText("Nombre:");

        jLblApellido.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLblApellido.setText("Apellido:");

        jLblOrden.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLblOrden.setText("Su orden es:");

        jTxfNombre.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        jBtnAceptar.setText("Aceptar");

        jBtnCancelar.setText("Cancelar");

        jBtnMetPago.setText("Método de Pago");
        jBtnMetPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMetPagoActionPerformed(evt);
            }
        });

        jBtnBorrar.setText("Borrar Datos");
        jBtnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBorrarActionPerformed(evt);
            }
        });

        jBtnMenu.setText("Menú");
        jBtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMenuActionPerformed(evt);
            }
        });

        jLblCedula.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLblCedula.setText("Cédula:");

        jTxfOrden.setEditable(false);
        jTxfOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxfOrdenActionPerformed(evt);
            }
        });

        jLblMtdoPago.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLblMtdoPago.setText("Método de pago:");

        jTxfMtdoPago.setEditable(false);

        jLblNOrden.setText("-----");

        jLblNOrden1.setText("N° Orden");

        jRdBtnFrancais.setText("Français");
        buttonGroup1.add(jRdBtnFrancais);
        jRdBtnFrancais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnFrancaisActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRdBtnSpanish);
        jRdBtnSpanish.setText("Español");
        jRdBtnSpanish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnSpanishActionPerformed(evt);
            }
        });

        jRdBtnEnglish.setText("English");
        buttonGroup1.add(jRdBtnEnglish);
        jRdBtnEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdBtnEnglishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(jLblNOrden1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblNOrden)
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLblNombre)
                        .addComponent(jLblApellido))
                    .addComponent(jLblCedula))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxfNombre)
                    .addComponent(jTxfApellido)
                    .addComponent(jTxfCedula))
                .addGap(81, 81, 81))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnCancelar)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRdBtnEnglish)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRdBtnFrancais)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnBorrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRdBtnSpanish)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxfOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnMenu))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblMtdoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxfMtdoPago)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnMetPago)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblNOrden1)
                        .addComponent(jLblNOrden)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNombre)
                    .addComponent(jTxfNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblApellido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCedula)
                    .addComponent(jTxfCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMtdoPago)
                    .addComponent(jTxfMtdoPago)
                    .addComponent(jBtnMetPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblOrden)
                    .addComponent(jTxfOrden)
                    .addComponent(jBtnMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAceptar)
                    .addComponent(jBtnCancelar)
                    .addComponent(jBtnBorrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRdBtnEnglish)
                    .addComponent(jRdBtnFrancais)
                    .addComponent(jRdBtnSpanish))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu3.setText("Opciones");

        jMnImPagWb.setText("Pagina Web");
        jMenu3.add(jMnImPagWb);
        jMnImPagWb.addMenuDragMouseListener(this);
        jMnImPagWb.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                jDialPagWeb dialo=new jDialPagWeb(null,true);
                dialo.setVisible(true);
                dialo.pack();
            }
        });
        jMenu3.add(jSeparator1);

        jMnImSalir.setText("Salir");
        jMnImSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnImSalirActionPerformed(evt);
            }
        });
        jMenu3.add(jMnImSalir);
        jMnImSalir.addMenuDragMouseListener(this);
        jMnImSalir.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                int valor = JOptionPane.showConfirmDialog(null, "¿Desea salir?", "Mensaje del Sistema",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (valor == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
            }
        });

        jMenuBar1.add(jMenu3);

        jMhelp.setText("Help");
        jMenuBar1.add(jMhelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRdBtnEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtnEnglishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdBtnEnglishActionPerformed

    private void jRdBtnSpanishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtnSpanishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdBtnSpanishActionPerformed

    private void jRdBtnFrancaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdBtnFrancaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRdBtnFrancaisActionPerformed

    private void jTxfOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxfOrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxfOrdenActionPerformed

    private void jBtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnMenuActionPerformed

    private void jBtnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnBorrarActionPerformed

    private void jBtnMetPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMetPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnMetPagoActionPerformed

    private void jMnImSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnImSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnImSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmEventos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnAceptar;
    private javax.swing.JButton jBtnBorrar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnMenu;
    private javax.swing.JButton jBtnMetPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblApellido;
    private javax.swing.JLabel jLblCedula;
    private javax.swing.JLabel jLblMtdoPago;
    private javax.swing.JLabel jLblNOrden;
    private javax.swing.JLabel jLblNOrden1;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblOrden;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMhelp;
    private javax.swing.JMenuItem jMnImPagWb;
    private javax.swing.JMenuItem jMnImSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRdBtnEnglish;
    private javax.swing.JRadioButton jRdBtnFrancais;
    private javax.swing.JRadioButton jRdBtnSpanish;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTxfApellido;
    private javax.swing.JTextField jTxfCedula;
    private javax.swing.JTextField jTxfMtdoPago;
    private javax.swing.JTextField jTxfNombre;
    private javax.swing.JTextField jTxfOrden;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowClosing(WindowEvent e) {
        int valor = JOptionPane.showConfirmDialog(this, "¿Desea salir?", "Mensaje del Sistema",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (valor == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    @Override
    public void windowOpened(WindowEvent e) {}

    @Override
    public void windowClosed(WindowEvent e) {}

    @Override
    public void windowIconified(WindowEvent e) {}

    @Override
    public void windowDeiconified(WindowEvent e) {}

    @Override
    public void windowActivated(WindowEvent e) {}

    @Override
    public void windowDeactivated(WindowEvent e) {}

    @Override
    public void componentResized(ComponentEvent e) {
        Component c = e.getComponent();
        x = c.getSize().width;
        y = c.getSize().height;

        setFont();
    }

    @Override
    public void componentMoved(ComponentEvent e) {}

    @Override
    public void componentShown(ComponentEvent e) {}

    @Override
    public void componentHidden(ComponentEvent e) {}

    @Override
    public void actionPerformed(ActionEvent e) {
        Object obj = e.getSource();
        if (obj == jBtnAceptar) {
            if (!jTxfNombre.getText().isEmpty() && !jTxfApellido.getText().isEmpty() && !jTxfCedula.getText().isEmpty() && !jTxfMtdoPago.getText().isEmpty() && !jTxfOrden.getText().isEmpty()) {
                int n = JOptionPane.showConfirmDialog(null, "¿Desea grabar los datos?", "Mensaje del Sistema",
                        JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (n == JOptionPane.OK_OPTION) {
                    JDialFact cuadroDialogo = new JDialFact(this, true);
                    cuadroDialogo.setTextJtxfNombres(jTxfNombre.getText(), jTxfApellido.getText());
                    cuadroDialogo.setTextJtxfCedula(jTxfCedula.getText());
                    cuadroDialogo.setTextJtxfMtdoPago(jTxfMtdoPago.getText());
                    cuadroDialogo.setTextJtxfOrden(jTxfOrden.getText());
                    cuadroDialogo.pack();
                    cuadroDialogo.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No estan todos los campos llenos", "Sistema", JOptionPane.ERROR_MESSAGE);
            }

        } else if (obj == jBtnCancelar) {
            System.exit(0);
        } else if (obj == jBtnMetPago) {
            JDialMetPago cuadroDialogo = new JDialMetPago(this, true);
            cuadroDialogo.pack();
            cuadroDialogo.setVisible(true);
            jTxfMtdoPago.setText(cuadroDialogo.get_Msg());
        } else if (obj == jBtnBorrar) {
            jTxfNombre.setText("");
            jTxfCedula.setText("");
            jTxfApellido.setText("");
            jTxfMtdoPago.setText("");
            jTxfOrden.setText("");
            jLblNOrden.setText("");
        } else if (obj == jBtnMenu) {
            JDialMenu cuadroDialogo = new JDialMenu(this, true);
            cuadroDialogo.pack();
            cuadroDialogo.setVisible(true);
            jTxfOrden.setText(cuadroDialogo.get_Msg());
        }
    }

    @Override
    public void menuSelected(MenuEvent e) {
        Object obj = e.getSource();
        if (obj == jMhelp) {
            int n = JOptionPane.showConfirmDialog(null, "¿Necesita ayuda?", "Mensaje del Sistema",
                    JOptionPane.YES_NO_OPTION);
            if (n == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(jMenuBar1, "Un asesor lo atendera", "Mensaje del sistema", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }

    @Override
    public void menuDeselected(MenuEvent e) {}

    @Override
    public void menuCanceled(MenuEvent e) {}

    @Override
    public void keyTyped(KeyEvent e) {}

    @Override
    public void keyPressed(KeyEvent e) {
        Object obj = e.getSource();
        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            if (obj == jBtnAceptar || obj == jTxfNombre || obj == jTxfApellido || obj == jTxfMtdoPago || obj == jTxfOrden || obj == jTxfCedula) {
                if (!jTxfNombre.getText().isEmpty() && !jTxfApellido.getText().isEmpty() && !jTxfCedula.getText().isEmpty() && !jTxfMtdoPago.getText().isEmpty() && !jTxfOrden.getText().isEmpty()) {
                    int n = JOptionPane.showConfirmDialog(null, "¿Desea grabar los datos?", "Mensaje del Sistema",
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if (n == JOptionPane.OK_OPTION) {
                        String datos = "\nNombre: " + jTxfNombre.getText() + "\nApellido: " + jTxfApellido.getText()
                                + "\nCedula: " + jTxfCedula.getText() + "\nMetodo de pago: " + jTxfMtdoPago.getText()
                                + "\nOrden:" + jTxfOrden.getText();
                        JOptionPane.showMessageDialog(null, "Su pedido es: " + datos, "Sistema", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No estan todos los campos llenos", "Sistema", JOptionPane.ERROR_MESSAGE);
                }

            } else if (obj == jBtnCancelar) {
                System.exit(0);
            } else if (obj == jBtnMetPago) {
                JDialMetPago cuadroDialogo = new JDialMetPago(this, true);
                cuadroDialogo.pack();
                cuadroDialogo.setVisible(true);
                jTxfMtdoPago.setText(cuadroDialogo.get_Msg());
            } else if (obj == jBtnBorrar) {
                jTxfNombre.setText("");
                jTxfCedula.setText("");
                jTxfApellido.setText("");
                jTxfMtdoPago.setText("");
                jTxfOrden.setText("");
            } else if (obj == jBtnMenu) {
                JDialMenu cuadroDialogo = new JDialMenu(this, true);
                cuadroDialogo.pack();
                cuadroDialogo.setVisible(true);
                jTxfOrden.setText(cuadroDialogo.get_Msg());
            }
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {}

    @Override
    public void focusGained(FocusEvent e) {
        jLblNOrden.getText();
    }

    @Override
    public void focusLost(FocusEvent e) {
        Random rnd = new Random();
        if (jLblNOrden.getText().equals("-----")) {
            if (!jTxfNombre.getText().isEmpty() && !jTxfApellido.getText().isEmpty() && !jTxfCedula.getText().isEmpty() && !jTxfMtdoPago.getText().isEmpty() && !jTxfOrden.getText().isEmpty()) {
                int n = (int) (rnd.nextDouble() * 100 + 1000);
                jLblNOrden.setText(String.valueOf(n));
            }
        }
    }

    @Override
    public void stateChanged(ChangeEvent e) {
        if (jRdBtnSpanish.isSelected() == true) {
            jRdBtnEnglish.setSelected(false);
            jRdBtnFrancais.setSelected(false);
            jLblNombre.setText("Nombre:");
            jLblApellido.setText("Apellido:");
            jLblCedula.setText("Cedula:");
            jLblMtdoPago.setText("Método de pago:");
            jLblOrden.setText("Su orden es");
            jLblNOrden1.setText("N°");
            jBtnAceptar.setText("Aceptar");
            jBtnCancelar.setText("Cancelar");
            jBtnMetPago.setText("Método de Pago");
            jBtnMenu.setText("Menú");
            jBtnBorrar.setText("Borrar Datos");
        }
        if (jRdBtnEnglish.isSelected() == true) {
            jRdBtnSpanish.setSelected(false);
            jRdBtnFrancais.setSelected(false);
            jLblNombre.setText("Name:");
            jLblApellido.setText("Last name:");
            jLblCedula.setText("Identification:");
            jLblMtdoPago.setText("Payment method:");
            jLblOrden.setText("Your order is");
            jLblNOrden1.setText("N°");
            jBtnAceptar.setText("Accept");
            jBtnCancelar.setText("Cancel");
            jBtnMetPago.setText("Payment method");
            jBtnMenu.setText("Menu");
            jBtnBorrar.setText("Delete data");
        }
        if (jRdBtnFrancais.isSelected() == true) {
            jRdBtnSpanish.setSelected(false);
            jRdBtnFrancais.setSelected(false);
            jLblNombre.setText("Nom:");
            jLblApellido.setText("Le nom:");
            jLblCedula.setText("Identité:");
            jLblMtdoPago.setText("Procédé de paiement:");
            jLblOrden.setText("Votre commande est");
            jLblNOrden1.setText("N°");
            jBtnAceptar.setText("Accepter");
            jBtnCancelar.setText("Annuler");
            jBtnMetPago.setText("Procédé de paiement");
            jBtnMenu.setText("Menu");
            jBtnBorrar.setText("Suprimmer les données");
        }
    }

    @Override
    public void menuDragMouseEntered(MenuDragMouseEvent e) {
        System.out.println("Arrastrando dentro del MenuItem");
    }

    @Override
    public void menuDragMouseExited(MenuDragMouseEvent e) {
        System.out.println("Arrastrando fuera del MenuItem");
    }

    @Override
    public void menuDragMouseDragged(MenuDragMouseEvent e) {
        System.out.println("Arrastrando dentro del MenuItem");
    }

    @Override
    public void menuDragMouseReleased(MenuDragMouseEvent e) {
        System.out.println("El puntero soltó el menú que estaba arrastrando");
    }

}
